name: zapland_web
description: Zapland Web

publish_to: "none"
version: 1.0.0+7

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # common
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.1.3
  sizer: ^2.0.15
  fluttertoast: ^8.0.9
  toastification: ^2.1.0
  gauge_indicator: ^0.4.3
  url_launcher: ^6.0.12
  encrypt: ^5.0.3
  flutter_native_splash: ^2.4.1
  routemaster: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  image: "assets/splash/splash.png"
  color: "F5F5F5"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env
    - assets/splash/
    - assets/roblox/

  fonts:
    - family: CarterOne
      fonts:
        - asset: assets/fonts/CarterOne/CarterOne-Regular.ttf
