name: zapland_web
description: Zapland Web

publish_to: "none"
version: 1.0.0+19

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # common
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.1.3
  sizer: ^2.0.15
  fluttertoast: ^8.0.9
  toastification: ^2.1.0
  gauge_indicator: ^0.4.3
  url_launcher: ^6.0.12
  encrypt: ^5.0.3
  flutter_native_splash: ^2.2.19
  routemaster: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  pointycastle: ^3.9.1
  device_info_plus: ^9.1.2
  # device_user_agent: ^0.1.1
  web: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFE000"
    theme_color: "#3DFB92"

flutter_native_splash:
  image: "assets/splash/splash.png"
  color: "F5F5F5"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env
    - assets/icon/icon.png
    - assets/splash/
    - assets/roblox/
    - assets/ogp/
    - assets/test/

  fonts:
    - family: CarterOne
      fonts:
        - asset: assets/fonts/CarterOne/CarterOne-Regular.ttf
